/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as CotacoesRouteImport } from './routes/cotacoes'
import { Route as IndexRouteImport } from './routes/index'

const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacoesRoute = CotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cotacoes': typeof CotacoesRoute
  '/fornecedores': typeof FornecedoresRoute
  '/mapa': typeof MapaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cotacoes': typeof CotacoesRoute
  '/fornecedores': typeof FornecedoresRoute
  '/mapa': typeof MapaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cotacoes': typeof CotacoesRoute
  '/fornecedores': typeof FornecedoresRoute
  '/mapa': typeof MapaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cotacoes' | '/fornecedores' | '/mapa'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cotacoes' | '/fornecedores' | '/mapa'
  id: '__root__' | '/' | '/cotacoes' | '/fornecedores' | '/mapa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CotacoesRoute: typeof CotacoesRoute
  FornecedoresRoute: typeof FornecedoresRoute
  MapaRoute: typeof MapaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacoes': {
      id: '/cotacoes'
      path: '/cotacoes'
      fullPath: '/cotacoes'
      preLoaderRoute: typeof CotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CotacoesRoute: CotacoesRoute,
  FornecedoresRoute: FornecedoresRoute,
  MapaRoute: MapaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
